name: BBCoreSpigot
version: 5.5.1
author: MJ

main: main.de.mj.bb.core.CoreSpigot
softdepend: [CoinsAPI, Vault, TimoCloud, VIPHide, LuckPerms, NetworkManagerBridge, FriendsAPIForPartyAndFriends, Clans-Spigot-Part, ProtocolLib, Skript]

commands:
   afk:
   fly:
   spawn:
   set:
   server:
   setrank:
   gotoserver:
   serverinfo:
   tps:
   bbreload: