name: BBCore
version: 5.2.1
author: MJ

main: de.mj.BattleBuild.core.Core
softdepend: [CoinsAPI, Vault, TimoCloud, VIPHide, LuckPerms, NetworkManagerBridge, FriendsAPIForPartyAndFriends, Clans-Spigot-Part, ProtocolLib, Skript]

commands:
   afk:
   spawn:
   set:
   server:
   setrank:
   gotoserver:
   serverinfo: