name: BBLobby
version: 4.1.2
author: MJ

main: de.mj.BattleBuild.lobby.Lobby
depend: [CoinsAPI, Vault, TimoCloud, VIPHide, LuckPerms, NetworkManagerBridge, FriendsAPIForPartyAndFriends, Clans-Spigot-Part, ProtocolLib]

commands:
   afk:
   spawn:
   set:
   server: