name: BBCore
version: 5.0.4
author: MJ

main: de.mj.BattleBuild.core.Core
softdepend: [CoinsAPI, Vault, TimoCloud, VIPHide, LuckPerms, NetworkManagerBridge, FriendsAPIForPartyAndFriends, Clans-Spigot-Part, ProtocolLib]

commands:
   afk:
   spawn:
   set:
   server:
   setrank: